//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informaion
    {
        public int id { get; set; }
        public Nullable<bool> CashOrReserve { get; set; }
        public Nullable<decimal> CashValue { get; set; }
        public Nullable<int> fromId { get; set; }
        public Nullable<int> toId { get; set; }
        public Nullable<int> travellerId { get; set; }
        public Nullable<int> carId { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> dateTravel { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual From From { get; set; }
        public virtual To To { get; set; }
        public virtual Traveller Traveller { get; set; }
        public virtual User User { get; set; }
    }
}
